### ISSUE TITLE
Denon does not watch files

### ISSUE THREAD

**Issue by clianor** [denosaurs/denon#79] opened 2020-07-22 02:56 UTC
**Describe the bug**
denon doesn't watch the file

**To Reproduce**
denon start

denon.json

```json
{
  "$schema": "https://deno.land/x/denon/schema.json",
  "allow": [
    "env",
    "net"
  ],
  "watch": true,
  "scripts": {
    "start": {
      "cmd": "deno run app.ts",
      "desc": "run my app.ts file",
      "env": {
        "PORT": "8000"
      },
      "unstable": true
    }
  },
  "watcher": {
    "interval": 350,
    "exts": ["js", "jsx", "ts", "tsx", "json"],
    "match": ["*.*"],
    "skip": ["*/.git/*"],
    "legacy": false
  }
}

```
**Setup**
- OS: Ubuntu on WSL2
- Deno version: 1.2.0
- Denon version: 2.2.1

**Comment by qu4k** [comment] 2020-07-22 07:09
Closing as duplicate of #72

**Closed by qu4k** 2020-07-22 07:09 UTC
Labels: bug, duplicate

**Comment by webdeb** [comment] 2020-11-04 23:27
@qu4k can you explain how is this dupe to #72 ?
