### ISSUE TITLE
v2.0.0 not working

### ISSUE THREAD

**Issue by David-Else** [denosaurs/denon#48] opened 2020-05-23 10:16 UTC
Please see attached screenshots. 

If I use `denon --allow-net run index.js` as per the README then I get a crash. If I use `denon run --allow-net index.js` it seems to work, but when I update the file nothing happens.

```
deno 1.0.2
```

![Screenshot from 2020-05-23 11-11-55](https://user-images.githubusercontent.com/12832280/82728250-21ff9d80-9ce7-11ea-96b4-26252f190748.png)
![Screenshot from 2020-05-23 11-12-28](https://user-images.githubusercontent.com/12832280/82728252-22983400-9ce7-11ea-8e10-575d44ee43fb.png)

**Comment by Qu4k** [comment] 2020-05-23 10:24
> denon --allow-net run index.js

Thanks for spotting that. It is a typo in the README.md

As for your issue we currently do not support deno `v1.0.2` as it was just released. I will look into it and update this issue.

**Comment by Qu4k** [comment] 2020-05-23 10:41
I managed to get `denon` working without any changes to the code in version `v1.0.2` of deno using vscode. I am running the oak example in our [examples/](https://github.com/denosaurs/denon/tree/master/examples) folder. I will investivate with windows.

**Comment by David-Else** [comment] 2020-05-23 10:45
I am using Linux. Here is the code in question:
```
import { Application, Router } from "https://deno.land/x/oak/mod.ts";

const dummyUsers = [
  { id: 1, firstName: "John", lastName: "Wick", age: 41 },
  { id: 2, firstName: "Joe", lastName: "Doe", age: 35 },
  { id: 3, firstName: "Brad", lastName: "Pitt", age: 50 },
];

const getById = (id) => {
  return dummyUsers.filter((user) => user.id == id);
};

const router = new Router();
const app = new Application();

router.get("/", (context) => {
  context.response.body = "Welcome to Oak example with Deno!";
});

router.get("/v1/users", (context) => {
  context.response.body = { users: dummyUsers };
});

router.get("/v1/users/:id", (context) => {
  if (
    context.params &&
    context.params.id &&
    !isNaN(parseInt(context.params.id))
  ) {
    const result = getById(context.params.id);
    if (result.length < 1) {
      context.response.status = 404;
      context.response.body = { error: `User ${context.params.id} not found` };
    } else {
      context.response.body = result[0];
    }
  } else {
    context.response.status = 400;
    context.response.body = { error: "Id must be number" };
  }
});

router.post("/v1/users", async (context) => {
  if (!context.request.hasBody) {
    context.response.status = 400;
    context.response.body = { error: "Request body cannot be empty" };
  } else {
    const { firstName, lastName, age } = (
      await context.request.body(true)
    ).value;
    const ageInt = parseInt(age);
    if (firstName && lastName && ageInt) {
      dummyUsers.push({
        id: dummyUsers.length + 1,
        firstName: firstName,
        lastName: lastName,
        age: ageInt,
      });
      context.response.status = 201;
      context.response.body = dummyUsers[dummyUsers.length - 1];
    } else {
      context.response.status = 400;
      context.response.body = { error: "Invalid payload's provided" };
    }
  }
});

router.put("/v1/users/:id", async (context) => {
  if (
    !context.params ||
    !context.params.id ||
    isNaN(parseInt(context.params.id) || !context.request.hasBody)
  ) {
    context.response.status = 400;
    context.response.body = { error: "Invalid request" };
  } else {
    const result = getById(context.params.id);
    if (result.length < 1) {
      context.response.status = 404;
      context.response.body = { error: `User ${context.params.id} not found` };
    } else {
      const id = context.params.id;
      const { firstName, lastName, age } = (await context.request.body()).value;
      const ageInt = parseInt(age);
      if (firstName && lastName && ageInt) {
        dummyUsers.splice(id - 1, 1, {
          id: id,
          firstName: firstName,
          lastName: lastName,
          age: ageInt,
        });
        context.response.status = 200;
        context.response.body = dummyUsers[id - 1];
      } else {
        context.response.status = 400;
        context.response.body = { error: "Invalid payload's provided" };
      }
    }
  }
});

router.delete("/v1/users/:id", (context) => {
  if (
    context.params &&
    context.params.id &&
    !isNaN(parseInt(context.params.id))
  ) {
    dummyUsers.splice(context.params.id - 1, 1);
    context.response.status = 204;
  } else {
    context.response.status = 400;
    context.response.body = { error: "Id must be number" };
  }
});

app.use(router.routes());
app.use(router.allowedMethods());
await app.listen({ port: 8080 });
```

**Comment by Qu4k** [comment] 2020-05-23 11:06
I managed to get it working on a fresh ubuntu machine with deno `1.0.2` using vim. If you can provide other steps for me to reproduce this issue I would be grateful 🌟

**Comment by David-Else** [comment] 2020-05-23 11:42
OK, I will make a new test case. Should denon tell me when a file has changed on the CLI?

**Comment by Qu4k** [comment] 2020-05-23 11:45
<img width="475" alt="Schermata 2020-05-23 alle 13 44 50" src="https://user-images.githubusercontent.com/12383260/82729872-95aba580-9cfb-11ea-8024-2e9101a5462a.png">
Should say something like this.

**Comment by David-Else** [comment] 2020-05-23 11:49
```
mkdir test
cd test
(make a file index.js with console.log("hello");)
denon run index.js

[denon] v2.0.0
[denon] watching path(s): *.*
[denon] watching extensions: ts,js,json
[denon] starting `deno run index.js`
hello
[denon] clean exit - waiting for changes before restart
```
change the file and nothing happens

**Comment by David-Else** [comment] 2020-05-23 11:51
I have a breakthrough! Edit it in another editor and it works. It is something in VS Code.

**Comment by Qu4k** [comment] 2020-05-23 13:37
Thanks for sharing, we will look into this strange behaviour.

**Comment by David-Else** [comment] 2020-05-23 14:37
Cheers. Did you manage to recreate the error OK?

**Comment by Qu4k** [comment] 2020-05-23 20:19
I recreated the error with a ubuntu vm. Strangely vscode sends an `access` event to the filesystem instead of a `modify` event. We added support for it (a3a0a3c0a3e24bf13e278b90a50447369692364f) so reloading on vscode on linux should be fine. I would be very grateful to you if you could test the new changes

**Comment by David-Else** [comment] 2020-05-23 21:18
I did `denon upgrade` and now it works :) Thanks for quick fix. It sounds weird that VS Code is doing that, maybe worth a bug report?

I tried to search around for ideas:

https://www.linuxquestions.org/questions/linux-general-1/difference-between-access-modify-change-330250/

> Access Time | atime | -ul
> This is the time that the file was last accessed, read or written to.
> 
> Modify Time | mtime | -l
> This is the time that the inode information (permissions, name, etc., the metadata, as it were) was last modified.
> 
> Change Time | ctime | -cl
> This is the last time the actual contents of the file were last modified.

So you are looking for the `change` time?

I seem to remember that Code uses chokidar, but I might be wrong. In this thread https://github.com/paulmillr/chokidar/issues/294 someone says regarding Linux:

> You will miss `change` events if you watch only the directory and not the files (depending on how the file was modified). If you only care about files being created, deleted, or moved, then yes, directory-level watchers should suffice. But chokidar does not provide an option for this.

Could this be involved?

Unfortunately there were errors at the end of the upgrade:
```
/home/david/.deno/bin/denon: line 4: unexpected EOF while looking for matching `"'
/home/david/.deno/bin/denon: line 5: syntax error: unexpected end of file
```

**Comment by Qu4k** [comment] 2020-05-24 11:19
We have two watchers, the main one which uses `Deno.watchFs` and is similar the the nodejs counterpart; the legacy one which looks at the modified time walking the current working directory.

> Unfortunately there were errors at the end of the upgrade:
At the end of `denon --upgrade`?

**Comment by David-Else** [comment] 2020-05-24 12:22
> I recreated the error with a ubuntu vm. Strangely vscode sends an access event to the filesystem instead of a modify event. 

I have found that VS Code is sending modify events in Linux as well as access events. Just run this and save any file in the directory:

```ts
const watcher = Deno.watchFs("./");
for await (const event of watcher) {
  console.log(">>>> event", event);
}
```
![modify-event](https://user-images.githubusercontent.com/12832280/82753862-1aacc280-9dc1-11ea-9519-5e2572679989.png)


> (errors) At the end of denon --upgrade?

Yes:
```
/home/david/.deno/bin/denon: line 4: unexpected EOF while looking for matching `"'
/home/david/.deno/bin/denon: line 5: syntax error: unexpected end of file
```

**Comment by Qu4k** [comment] 2020-05-24 15:25
with 003058dd9558233f7fcac7dcd49a3e567a0928bb linux fsevents are better handled

**Comment by David-Else** [comment] 2020-05-24 16:03
I did an `denon --upgrade` and it seems to work great :) It comes from master I assume.

Can I do a versioned update? For example, when 2.1 comes out can I stick with that somehow? Cheers!

**Comment by Qu4k** [comment] 2020-05-24 19:10
We will surely implement versioned upgrade when we redo CLI options

**Comment by Qu4k** [comment] 2020-05-24 19:11
I am now closing since this particular issue is solved 🌟

**Closed by Qu4k** 2020-05-24 19:11 UTC
Labels: bug
