### ISSUE TITLE
Can't find scripts

### ISSUE THREAD

**Issue by ryanwhite04** [denosaurs/denon#65] opened 2020-06-11 02:43 UTC
Denon can't see scripts property in denon.config.ts.

**To Reproduce**
```ts
// denon.config.ts
import { DenonConfig } from "https://deno.land/x/denon/mod.ts";

const config: DenonConfig = {
  scripts: {
    build: {
      cmd: "build.ts",
      desc: "run my build.ts file",
    },
  },
};
export default config;
```

 run `denon` to view scripts
output is
```bash
[denon] v2.1.0
[denon] It looks like you don't have any scripts...
[denon] You can add scripts to your `denon.config.ts` file. Check the docs.
```

**Expected behavior**
denon should list *build* as a script

**Setup**

-   OS: Windows
-   Deno version: 1.0.4
-   Denon version: 2.1.0

**Comment by Qu4k** [comment] 2020-06-11 08:53
I made a pull request with a possible fix.  When it's merged you should probably reinstall denon with the command in the README (added some permissions as `import` now requires `--allow-net`) and test if the issue is solved.

Thanks @ryanwhite04

**Comment by ryanwhite04** [comment] 2020-06-11 09:46
Yeah it works now, Thanks!

**Closed** 2020-06-11 10:16 UTC
Labels: bug
